### ISSUE TITLE
OBS 27.2.4 (Fedora Linux 35) crashes immediately upon applying filter

### ISSUE THREAD

**Issue by benblasco** [exeldro/obs-source-record#50]
After installing Source Record 0.3.0 and attempting to apply the filter to any source, OBS immediately crashes. The plugin is effectively unusable as a result.

Happy to supply as much information as possible to resolve this issue, and would love some guidance on where to begin so I can help improve the plugin!

**Comment by ogmkp** [comment]
Reproduced here on Debian 11 with source record 0.3.2 in OBS 29.0.2.

log:

```
info: User added filter 'Source Record' (source_record_filter) to source 'Source média'
info: NV12 texture support not available
info: P010 texture support not available
error: VAAPI: Failed to open device ''
error: VAAPI: Failed to open device ''
Erreur de segmentation
```

gdb backtrace:

```
[Thread 0x7fff163aa700 (LWP 96912) exited]
info: User added filter 'Source Record' (source_record_filter) to source 'Source média'
[New Thread 0x7fff163aa700 (LWP 96918)]
[New Thread 0x7fff15ba9700 (LWP 96919)]
[New Thread 0x7fff13f51700 (LWP 96920)]
[New Thread 0x7fff13317700 (LWP 96921)]
[New Thread 0x7fff12715700 (LWP 96922)]
[New Thread 0x7fff11f14700 (LWP 96923)]
[New Thread 0x7fff11713700 (LWP 96924)]
[New Thread 0x7fff10f12700 (LWP 96925)]
[New Thread 0x7fff10711700 (LWP 96926)]
[New Thread 0x7fff0ff10700 (LWP 96927)]
info: NV12 texture support not available
info: P010 texture support not available
[Thread 0x7fff10711700 (LWP 96926) exited]
[Thread 0x7fff10f12700 (LWP 96925) exited]
[Thread 0x7fff11713700 (LWP 96924) exited]
[Thread 0x7fff11f14700 (LWP 96923) exited]
[Thread 0x7fff12715700 (LWP 96922) exited]
[Thread 0x7fff13317700 (LWP 96921) exited]
[Thread 0x7fff13f51700 (LWP 96920) exited]
[Thread 0x7fff15ba9700 (LWP 96919) exited]
[Thread 0x7fff163aa700 (LWP 96918) exited]
[New Thread 0x7fff13317700 (LWP 96928)]
[New Thread 0x7fff13f51700 (LWP 96929)]
[New Thread 0x7fff15ba9700 (LWP 96930)]
[New Thread 0x7fff163aa700 (LWP 96931)]
[New Thread 0x7fff12715700 (LWP 96932)]
[New Thread 0x7fff11f14700 (LWP 96933)]
[New Thread 0x7fff11713700 (LWP 96934)]
[New Thread 0x7fff10f12700 (LWP 96935)]
[New Thread 0x7fff10711700 (LWP 96936)]
[Thread 0x7fff10711700 (LWP 96936) exited]
[Thread 0x7fff10f12700 (LWP 96935) exited]
[Thread 0x7fff11713700 (LWP 96934) exited]
[Thread 0x7fff11f14700 (LWP 96933) exited]
[Thread 0x7fff12715700 (LWP 96932) exited]
[Thread 0x7fff13f51700 (LWP 96929) exited]
[Thread 0x7fff15ba9700 (LWP 96930) exited]
[Thread 0x7fff163aa700 (LWP 96931) exited]
[Thread 0x7fff13317700 (LWP 96928) exited]
[New Thread 0x7fff163aa700 (LWP 96937)]
[New Thread 0x7fff15ba9700 (LWP 96938)]
[New Thread 0x7fff13f51700 (LWP 96939)]
[New Thread 0x7fff13317700 (LWP 96940)]
[New Thread 0x7fff12715700 (LWP 96941)]
[New Thread 0x7fff11f14700 (LWP 96942)]
[New Thread 0x7fff11713700 (LWP 96943)]
[New Thread 0x7fff10f12700 (LWP 96944)]
[New Thread 0x7fff10711700 (LWP 96945)]
[Thread 0x7fff10f12700 (LWP 96944) exited]
[Thread 0x7fff11713700 (LWP 96943) exited]
[Thread 0x7fff11f14700 (LWP 96942) exited]
[Thread 0x7fff12715700 (LWP 96941) exited]
[Thread 0x7fff10711700 (LWP 96945) exited]
[Thread 0x7fff13317700 (LWP 96940) exited]
[Thread 0x7fff13f51700 (LWP 96939) exited]
[Thread 0x7fff15ba9700 (LWP 96938) exited]
[Thread 0x7fff163aa700 (LWP 96937) exited]
[New Thread 0x7fff13317700 (LWP 96946)]
[New Thread 0x7fff13f51700 (LWP 96947)]
[New Thread 0x7fff15ba9700 (LWP 96948)]
[New Thread 0x7fff163aa700 (LWP 96949)]
[New Thread 0x7fff12715700 (LWP 96950)]
[New Thread 0x7fff11f14700 (LWP 96951)]
[New Thread 0x7fff11713700 (LWP 96952)]
[New Thread 0x7fff10f12700 (LWP 96953)]
[New Thread 0x7fff10711700 (LWP 96954)]
[Thread 0x7fff11713700 (LWP 96952) exited]
[Thread 0x7fff11f14700 (LWP 96951) exited]
[Thread 0x7fff12715700 (LWP 96950) exited]
[Thread 0x7fff10711700 (LWP 96954) exited]
[Thread 0x7fff10f12700 (LWP 96953) exited]
[Thread 0x7fff163aa700 (LWP 96949) exited]
[Thread 0x7fff15ba9700 (LWP 96948) exited]
[Thread 0x7fff13f51700 (LWP 96947) exited]
[Thread 0x7fff13317700 (LWP 96946) exited]
error: VAAPI: Failed to open device ''
error: VAAPI: Failed to open device ''
--Type <RET> for more, q to quit, c to continue without paging--q
Quit
(gdb) bt
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:572
#1  0x00007fff54709b00 in  () at /usr/local//lib/obs-plugins/obs-ffmpeg.so
#2  0x00007ffff553574d in obs_properties_apply_settings_internal () at /usr/local/lib/libobs.so.0
#3  0x00007ffff5535796 in obs_properties_apply_settings_internal () at /usr/local/lib/libobs.so.0
#4  0x00007ffff5543eb0 in obs_source_properties () at /usr/local/lib/libobs.so.0
#5  0x00005555556346cd in  ()
#6  0x00007ffff4b7eff1 in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff59e342e in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff58fb15f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff4b52fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff4b55a01 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff4baae93 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff2c54e6b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff2c55118 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff2c551cf in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff4baa51f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff4b5198b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff4b59c00 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00005555555de044 in main ()
(gdb) 
```
